name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        MERRIAM_WEBSTER_API_KEY: ${{ secrets.MERRIAM_WEBSTER_API_KEY }}
      run: |
        pytest --junitxml=test_results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test_results.xml

    - name: Build Docker image
      run: |
        docker build -t cli:1.0 .

    - name: Save Docker image as a tar file
      run: |
        docker save -o cli.tar cli:1.0

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: cli-docker-image
        path: cli.tar